# Generated by Django 5.2 on 2025-04-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.JSONField()),
                ('mode', models.JSONField()),
                ('value_counts', models.JSONField()),
                ('null_counts', models.JSONField()),
                ('dtypes', models.JSONField()),
                ('duplicates_removed', models.IntegerField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadsession')),
            ],
        ),
    ]
